window.NexoData = (() => {
  const categories = [
    { label: "Padaria", keys: ["padaria", "bakery", "confeitaria"] },
    { label: "Restaurante", keys: ["restaurante", "restaurant"] },
    { label: "Cafeteria", keys: ["cafeteria", "café", "cafe"] },
    { label: "Barbearia", keys: ["barbearia", "barber", "cabelo"] },
    { label: "Salão de beleza", keys: ["salao", "salão", "beleza", "beauty"] },
    { label: "Academia", keys: ["academia", "gym", "fitness"] },
    { label: "Oficina mecânica", keys: ["oficina", "mecanica", "mecânica", "auto"] },
    { label: "Clínica odontológica", keys: ["odonto", "dentista", "dental"] },
    { label: "Clínica médica", keys: ["clinica", "clínica", "medico", "médico"] },
    { label: "Pet shop", keys: ["pet"] },
    { label: "Farmácia", keys: ["farmacia", "farmácia", "pharmacy"] },
    { label: "Imobiliária", keys: ["imobili"] },
    { label: "Advocacia", keys: ["advog", "advoc"] },
    { label: "Mercado", keys: ["mercado", "mercadinho", "supermercado"] },
  ];

  const leads = [
    {
      id: "demo-1",
      name: "Padaria São Joaquim",
      category: "Padaria",
      address: "Rua Harmonia, 412 — Vila Madalena, São Paulo",
      city: "São Paulo",
      neighborhood: "Vila Madalena",
      rating: 4.7,
      reviews: 318,
      phone: "(11) 3812-4409",
      website: "",
      hours: {
        openNow: true,
        closesAt: "19:00",
        summary: "Aberto · fecha às 19:00",
        weekdayText: [
          "segunda-feira: 06:00 – 19:00",
          "terça-feira: 06:00 – 19:00",
          "quarta-feira: 06:00 – 19:00",
          "quinta-feira: 06:00 – 19:00",
          "sexta-feira: 06:00 – 19:00",
          "sábado: 06:00 – 18:00",
          "domingo: 07:00 – 14:00",
        ],
        raw: "segunda-feira: 06:00 – 19:00 | terça-feira: 06:00 – 19:00",
      },
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Padaria%20S%C3%A3o%20Joaquim%20Vila%20Madalena",
      coords: { lat: -23.5468, lng: -46.6912 },
    },
    {
      id: "demo-2",
      name: "Pão & Brasa Forno a Lenha",
      category: "Padaria",
      address: "Rua dos Pinheiros, 890 — Pinheiros, São Paulo",
      city: "São Paulo",
      neighborhood: "Pinheiros",
      rating: 4.5,
      reviews: 204,
      phone: "(11) 3062-1188",
      website: "",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Pao%20Brasa%20Pinheiros",
      coords: { lat: -23.5661, lng: -46.6824 },
    },
    {
      id: "demo-3",
      name: "Confeitaria Dona Lina",
      category: "Padaria",
      address: "Av. Rebouças, 1501 — Pinheiros, São Paulo",
      city: "São Paulo",
      neighborhood: "Pinheiros",
      rating: 4.8,
      reviews: 91,
      phone: "(11) 3085-2210",
      website: "https://donalina.example",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Confeitaria%20Dona%20Lina%20Pinheiros",
      coords: { lat: -23.5614, lng: -46.6738 },
    },
    {
      id: "demo-3b",
      name: "Padaria da Vila",
      category: "Padaria",
      address: "Rua Wisard, 140 — Vila Madalena, São Paulo",
      city: "São Paulo",
      neighborhood: "Vila Madalena",
      rating: 4.6,
      reviews: 187,
      phone: "(11) 3812-7755",
      website: "",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Padaria%20da%20Vila%20Madalena",
      coords: { lat: -23.5496, lng: -46.6934 },
    },
    {
      id: "demo-3c",
      name: "Forno da Faria Lima",
      category: "Padaria",
      address: "Av. Brigadeiro Faria Lima, 1711 — Pinheiros, São Paulo",
      city: "São Paulo",
      neighborhood: "Pinheiros",
      rating: 4.4,
      reviews: 62,
      phone: "",
      website: "",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Forno%20da%20Faria%20Lima",
      coords: { lat: -23.5718, lng: -46.6895 },
    },
    {
      id: "demo-4",
      name: "Barbearia Corte Fino",
      category: "Barbearia",
      address: "Rua Teodoro Sampaio, 1020 — Pinheiros, São Paulo",
      city: "São Paulo",
      neighborhood: "Pinheiros",
      rating: 4.9,
      reviews: 612,
      phone: "(11) 98912-3344",
      website: "",
      hours: {
        openNow: true,
        closesAt: "20:00",
        summary: "Aberto · fecha às 20:00",
        weekdayText: ["segunda a sábado: 09:00 – 20:00", "domingo: fechado"],
        raw: "segunda a sábado: 09:00 – 20:00 | domingo: fechado",
      },
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Barbearia%20Corte%20Fino%20Pinheiros",
      coords: { lat: -23.5572, lng: -46.6771 },
    },
    {
      id: "demo-5",
      name: "Navalha Club",
      category: "Barbearia",
      address: "Rua Augusta, 2211 — Jardins, São Paulo",
      city: "São Paulo",
      neighborhood: "Jardins",
      rating: 4.4,
      reviews: 147,
      phone: "(11) 3231-0909",
      website: "https://navalhaclub.example",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Navalha%20Club%20Augusta",
      coords: { lat: -23.5589, lng: -46.6604 },
    },
    {
      id: "demo-6",
      name: "Oficina Ipiranga 24h",
      category: "Oficina mecânica",
      address: "Rua Silva Bueno, 455 — Ipiranga, São Paulo",
      city: "São Paulo",
      neighborhood: "Ipiranga",
      rating: 4.6,
      reviews: 389,
      phone: "(11) 2273-5512",
      website: "",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Oficina%20Ipiranga%2024h",
      coords: { lat: -23.5912, lng: -46.6098 },
    },
    {
      id: "demo-7",
      name: "Auto Center Bela Vista",
      category: "Oficina mecânica",
      address: "Rua 13 de Maio, 88 — Bela Vista, São Paulo",
      city: "São Paulo",
      neighborhood: "Bela Vista",
      rating: 4.1,
      reviews: 73,
      phone: "(11) 3255-8080",
      website: "",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Auto%20Center%20Bela%20Vista",
      coords: { lat: -23.561, lng: -46.646 },
    },
    {
      id: "demo-8",
      name: "Clínica Sorriso Pinheiros",
      category: "Clínica odontológica",
      address: "Rua Ferreira de Araújo, 202 — Pinheiros, São Paulo",
      city: "São Paulo",
      neighborhood: "Pinheiros",
      rating: 4.8,
      reviews: 256,
      phone: "(11) 3031-7766",
      website: "",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Clinica%20Sorriso%20Pinheiros",
      coords: { lat: -23.5678, lng: -46.6919 },
    },
    {
      id: "demo-9",
      name: "Odonto Prime Jardins",
      category: "Clínica odontológica",
      address: "Alameda Santos, 740 — Jardins, São Paulo",
      city: "São Paulo",
      neighborhood: "Jardins",
      rating: 4.3,
      reviews: 118,
      phone: "(11) 3284-1010",
      website: "https://odontoprime.example",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Odonto%20Prime%20Jardins",
      coords: { lat: -23.5684, lng: -46.6512 },
    },
    {
      id: "demo-10",
      name: "Pet House Moema",
      category: "Pet shop",
      address: "Av. Ibirapuera, 2100 — Moema, São Paulo",
      city: "São Paulo",
      neighborhood: "Moema",
      rating: 4.7,
      reviews: 421,
      phone: "(11) 5055-2323",
      website: "",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Pet%20House%20Moema",
      coords: { lat: -23.6011, lng: -46.6652 },
    },
    {
      id: "demo-11",
      name: "Academia Bloco 9",
      category: "Academia",
      address: "Rua Fradique Coutinho, 50 — Vila Madalena, São Paulo",
      city: "São Paulo",
      neighborhood: "Vila Madalena",
      rating: 4.6,
      reviews: 980,
      phone: "(11) 3816-4400",
      website: "",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Academia%20Bloco%209%20Vila%20Madalena",
      coords: { lat: -23.5512, lng: -46.6901 },
    },
    {
      id: "demo-12",
      name: "Café Miúdo",
      category: "Cafeteria",
      address: "Rua Aspicuelta, 333 — Vila Madalena, São Paulo",
      city: "São Paulo",
      neighborhood: "Vila Madalena",
      rating: 4.9,
      reviews: 540,
      phone: "(11) 3815-9090",
      website: "",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Cafe%20Miudo%20Vila%20Madalena",
      coords: { lat: -23.5489, lng: -46.6928 },
    },
    {
      id: "demo-13",
      name: "Trattoria do Beco",
      category: "Restaurante",
      address: "Rua dos Ingleses, 19 — Bela Vista, São Paulo",
      city: "São Paulo",
      neighborhood: "Bela Vista",
      rating: 4.5,
      reviews: 872,
      phone: "(11) 3266-4545",
      website: "",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Trattoria%20do%20Beco%20Bela%20Vista",
      coords: { lat: -23.5594, lng: -46.6448 },
    },
    {
      id: "demo-14",
      name: "Imobiliária Largo do Arouche",
      category: "Imobiliária",
      address: "Largo do Arouche, 120 — República, São Paulo",
      city: "São Paulo",
      neighborhood: "República",
      rating: 4.2,
      reviews: 64,
      phone: "(11) 3223-1717",
      website: "",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Imobiliaria%20Largo%20do%20Arouche",
      coords: { lat: -23.5418, lng: -46.6441 },
    },
    {
      id: "demo-15",
      name: "Padaria União de Botafogo",
      category: "Padaria",
      address: "Rua Voluntários da Pátria, 88 — Botafogo, Rio de Janeiro",
      city: "Rio de Janeiro",
      neighborhood: "Botafogo",
      rating: 4.6,
      reviews: 277,
      phone: "(21) 2266-8181",
      website: "",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Padaria%20Uniao%20Botafogo",
      coords: { lat: -22.9512, lng: -43.1844 },
    },
    {
      id: "demo-16",
      name: "Barbearia Copacabana 64",
      category: "Barbearia",
      address: "Av. Nossa Sra. de Copacabana, 640 — Copacabana, Rio de Janeiro",
      city: "Rio de Janeiro",
      neighborhood: "Copacabana",
      rating: 4.8,
      reviews: 733,
      phone: "(21) 98810-2200",
      website: "",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Barbearia%20Copacabana%2064",
      coords: { lat: -22.9711, lng: -43.1862 },
    },
    {
      id: "demo-17",
      name: "Clínica Leblon Odonto",
      category: "Clínica odontológica",
      address: "Av. Ataulfo de Paiva, 320 — Leblon, Rio de Janeiro",
      city: "Rio de Janeiro",
      neighborhood: "Leblon",
      rating: 4.4,
      reviews: 190,
      phone: "(21) 2512-4040",
      website: "https://leblonodonto.example",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Clinica%20Leblon%20Odonto",
      coords: { lat: -22.9842, lng: -43.2231 },
    },
    {
      id: "demo-18",
      name: "Oficina Humaitá Diesel",
      category: "Oficina mecânica",
      address: "Rua Humaitá, 275 — Humaitá, Rio de Janeiro",
      city: "Rio de Janeiro",
      neighborhood: "Humaitá",
      rating: 4.3,
      reviews: 156,
      phone: "(21) 2537-0099",
      website: "",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Oficina%20Humaita%20Diesel",
      coords: { lat: -22.9564, lng: -43.1988 },
    },
    {
      id: "demo-19",
      name: "Pet Rio Lagoa",
      category: "Pet shop",
      address: "Rua Jardim Botânico, 580 — Lagoa, Rio de Janeiro",
      city: "Rio de Janeiro",
      neighborhood: "Lagoa",
      rating: 4.7,
      reviews: 344,
      phone: "(21) 2294-6161",
      website: "",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Pet%20Rio%20Lagoa",
      coords: { lat: -22.9648, lng: -43.2175 },
    },
    {
      id: "demo-20",
      name: "Padaria Savassi da Esquina",
      category: "Padaria",
      address: "Rua Pernambuco, 1100 — Savassi, Belo Horizonte",
      city: "Belo Horizonte",
      neighborhood: "Savassi",
      rating: 4.8,
      reviews: 501,
      phone: "(31) 3261-3030",
      website: "",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Padaria%20Savassi%20da%20Esquina",
      coords: { lat: -19.9378, lng: -43.9356 },
    },
    {
      id: "demo-21",
      name: "Academia Serra do Curral",
      category: "Academia",
      address: "Av. do Contorno, 6400 — Savassi, Belo Horizonte",
      city: "Belo Horizonte",
      neighborhood: "Savassi",
      rating: 4.5,
      reviews: 812,
      phone: "(31) 3223-8881",
      website: "",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Academia%20Serra%20do%20Curral",
      coords: { lat: -19.9399, lng: -43.9312 },
    },
    {
      id: "demo-22",
      name: "Escritório Menezes Advogados",
      category: "Advocacia",
      address: "Rua da Bahia, 1148 — Lourdes, Belo Horizonte",
      city: "Belo Horizonte",
      neighborhood: "Lourdes",
      rating: 4.9,
      reviews: 88,
      phone: "(31) 3271-4545",
      website: "",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Menezes%20Advogados%20Lourdes",
      coords: { lat: -19.9314, lng: -43.9388 },
    },
    {
      id: "demo-23",
      name: "Mercadinho da Pampulha",
      category: "Mercado",
      address: "Av. Pedro I, 2900 — Pampulha, Belo Horizonte",
      city: "Belo Horizonte",
      neighborhood: "Pampulha",
      rating: 4.2,
      reviews: 210,
      phone: "(31) 3491-2020",
      website: "",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Mercadinho%20da%20Pampulha",
      coords: { lat: -19.8522, lng: -43.9764 },
    },
    {
      id: "demo-24",
      name: "Salão Casa Vermelha",
      category: "Salão de beleza",
      address: "Rua Oscar Freire, 480 — Jardins, São Paulo",
      city: "São Paulo",
      neighborhood: "Jardins",
      rating: 4.7,
      reviews: 263,
      phone: "(11) 3088-1717",
      website: "",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Salao%20Casa%20Vermelha%20Oscar%20Freire",
      coords: { lat: -23.5619, lng: -46.6702 },
    },
    {
      id: "demo-25",
      name: "Farmácia do Largo da Batata",
      category: "Farmácia",
      address: "Rua Cardeal Arcoverde, 77 — Pinheiros, São Paulo",
      city: "São Paulo",
      neighborhood: "Pinheiros",
      rating: 4.1,
      reviews: 97,
      phone: "(11) 3813-1212",
      website: "https://farmacialargo.example",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Farmacia%20Largo%20da%20Batata",
      coords: { lat: -23.5672, lng: -46.7021 },
    },
    {
      id: "demo-26",
      name: "Clínica Vida Lourdes",
      category: "Clínica médica",
      address: "Rua Sergipe, 1440 — Lourdes, Belo Horizonte",
      city: "Belo Horizonte",
      neighborhood: "Lourdes",
      rating: 4.6,
      reviews: 142,
      phone: "(31) 3291-7000",
      website: "",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Clinica%20Vida%20Lourdes",
      coords: { lat: -19.9328, lng: -43.9371 },
    },
    {
      id: "demo-27",
      name: "Café do Alto da Glória",
      category: "Cafeteria",
      address: "Rua do Catete, 210 — Glória, Rio de Janeiro",
      city: "Rio de Janeiro",
      neighborhood: "Glória",
      rating: 4.4,
      reviews: 129,
      phone: "(21) 2205-3033",
      website: "",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Cafe%20Alto%20da%20Gloria",
      coords: { lat: -22.9214, lng: -43.1768 },
    },
    {
      id: "demo-28",
      name: "Restaurante Mineiro da Savassi",
      category: "Restaurante",
      address: "Rua Tomé de Souza, 70 — Savassi, Belo Horizonte",
      city: "Belo Horizonte",
      neighborhood: "Savassi",
      rating: 4.7,
      reviews: 1104,
      phone: "(31) 3264-0091",
      website: "",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Restaurante%20Mineiro%20Savassi",
      coords: { lat: -19.9366, lng: -43.9379 },
    },
  ];

  const osmFilters = {
    padaria: ['["shop"="bakery"]', '["shop"="pastry"]'],
    restaurante: ['["amenity"="restaurant"]'],
    cafeteria: ['["amenity"="cafe"]'],
    barbearia: ['["shop"="hairdresser"]', '["craft"="barber"]'],
    salao: ['["shop"="beauty"]', '["shop"="hairdresser"]'],
    academia: ['["leisure"="fitness_centre"]', '["leisure"="sports_centre"]'],
    oficina: ['["shop"="car_repair"]'],
    odonto: ['["amenity"="dentist"]'],
    clinica: ['["amenity"="clinic"]', '["amenity"="doctors"]'],
    pet: ['["shop"="pet"]'],
    farmacia: ['["amenity"="pharmacy"]'],
    imobili: ['["office"="estate_agent"]'],
    advoc: ['["office"="lawyer"]'],
    mercado: ['["shop"="convenience"]', '["shop"="supermarket"]'],
  };

  const googleTypes = {
    padaria: "bakery",
    restaurante: "restaurant",
    cafeteria: "cafe",
    barbearia: "hair_care",
    salao: "beauty_salon",
    academia: "gym",
    oficina: "car_repair",
    odonto: "dentist",
    clinica: "doctor",
    pet: "pet_store",
    farmacia: "pharmacy",
    imobili: "real_estate_agency",
    advoc: "lawyer",
    mercado: "supermarket",
  };

  function normalize(text) {
    return (text || "")
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "");
  }

  function matchKey(niche) {
    const n = normalize(niche);
    const found = categories.find((c) => c.keys.some((k) => n.includes(normalize(k)) || normalize(k).includes(n)));
    if (found) {
      const key = found.keys[0];
      if (osmFilters[key]) return key;
      if (key.includes("padaria") || key === "bakery") return "padaria";
      if (key.includes("restaurant")) return "restaurante";
      if (key.includes("cafe")) return "cafeteria";
      if (key.includes("barber") || key.includes("cabelo")) return "barbearia";
      if (key.includes("salao") || key.includes("beleza")) return "salao";
      if (key.includes("gym") || key.includes("academia")) return "academia";
      if (key.includes("oficina") || key.includes("auto")) return "oficina";
      if (key.includes("odonto") || key.includes("dent")) return "odonto";
      if (key.includes("clinic") || key.includes("medico")) return "clinica";
      if (key.includes("pet")) return "pet";
      if (key.includes("farmac")) return "farmacia";
      if (key.includes("imobili")) return "imobili";
      if (key.includes("advog")) return "advoc";
      if (key.includes("mercado")) return "mercado";
    }
    if (n.includes("pada") || n.includes("baker")) return "padaria";
    if (n.includes("restau")) return "restaurante";
    if (n.includes("cafe")) return "cafeteria";
    if (n.includes("barbe") || n.includes("cabel")) return "barbearia";
    if (n.includes("salao") || n.includes("belez")) return "salao";
    if (n.includes("academ") || n.includes("gym")) return "academia";
    if (n.includes("ofici") || n.includes("mecan")) return "oficina";
    if (n.includes("odonto") || n.includes("denti")) return "odonto";
    if (n.includes("clini") || n.includes("medic")) return "clinica";
    if (n.includes("pet")) return "pet";
    if (n.includes("farmac")) return "farmacia";
    if (n.includes("imob")) return "imobili";
    if (n.includes("advog")) return "advoc";
    if (n.includes("mercad")) return "mercado";
    return "restaurante";
  }

  function searchDemo(niche, place) {
    const n = normalize(niche);
    const p = normalize(place);
    const nicheTokens = n.split(/\s+/).filter((t) => t.length > 3);
    const cities = [
      ["belo horizonte", "belo horizonte"],
      ["rio de janeiro", "rio de janeiro"],
      ["sao paulo", "sao paulo"],
    ];
    const cityKey = cities.find(([key]) => p.includes(key))?.[0];

    return leads.filter((lead) => {
      const blob = normalize(`${lead.category} ${lead.name} ${lead.city}`);
      const nicheOk =
        !nicheTokens.length ||
        nicheTokens.some((token) => blob.includes(token) || normalize(lead.category).includes(token));
      const cityOk = !cityKey || normalize(lead.city).includes(cityKey);
      return nicheOk && cityOk;
    });
  }

  return { leads, categories, osmFilters, googleTypes, matchKey, searchDemo, normalize };
})();
